---
# Handlers para el rol network-monitor

- name: restart supervisord
  systemd:
    name: supervisor
    state: restarted
  become: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes