---
- name: "User security hardening | Determine platform"
  block:
    - name: "Include Linux hardening tasks"
      import_tasks: linux.yml
      when: ansible_os_family != 'Windows'

    - name: "Include Windows hardening tasks"
      import_tasks: windows.yml
      when: ansible_os_family == 'Windows'
  tags:
    - security
    - hardening
